apiVersion: v1
kind: ReplicationController
metadata:
  name: servicename
spec:
  replicas: 3
  selector:
    service: servicename
  template:
    metadata:
      name: servicename
      labels:
        service: servicename #must match the selector of the rc, used for linking pods to services
    spec:
      containers: #many containers can be specified here that will be scheduled together onto the same host
      - name: aboutme #first container
        image: docker-sandbox.concurtech.net/muserviceshell/service #container image location
        ports:
        - containerPort: 8080 #port running inside and outside the container on the pod IP address
        #  hostPort: 3000 #not required but shown here, can be used to expose the container port directly on the kubernetes node
        livenessProbe: #health check configuration
          httpGet: #http shown here, you can also detail out a command\script to execute inside the container that expects a 0 status code.
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1