apiVersion: v1
kind: Service
metadata:
  name: servicename
spec:
  ports:
    -
      port: 8080 # internal port for communication between internal pods and services using the service name
      targetPort: 8080 # port on the POD
  selector:
    service: servicename
  type: ClusterIP
