Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/centos-6.6-64-puppet-enterprise"
  config.vm.network "private_network", ip: "10.29.202.20"

  config.vm.box_check_update = false

 
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  
  config.vm.provider "virtualbox" do |vb, override|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.gui = false
  end  
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  
  config.vm.provision "shell", inline: <<-SHELL
    #sudo yum install -y  "java-1.7.0-openjdk"
    yum install -y java-1.8.0-openjdk-devel
	yum install -y git

    sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    sudo yum install -y jenkins
    sudo service jenkins start
    sudo chkconfig jenkins on
    
   # sudo chown -R jenkins:jenkins /var/lib/jenkins/
   # sudo chmod -R a+rw /var/lib/jenkins/
  #  sudo service jenkins start
    
    #open ports 	  
	sudo iptables -I INPUT 1 -m state --state NEW -m tcp -p tcp --dport 8080 -j ACCEPT
	#sudo service iptables status
	sudo iptables-save | sudo tee /etc/sysconfig/iptables 
	sudo service iptables restart $ iptables -F

   SHELL
end

